### ISSUE TITLE
arm64 docker images

### ISSUE THREAD

**Issue by penchantlabs** [discuitnet/discuit#122]
Would be much appreciated if arm64 docker images could be published so that I can build on my server.

Thanks.

**Comment by Codycody31** [comment]
Arm64 would be nice to have, it was originally on my requirements for the docker image but due to complexity and time only amd64 was supported. If I remember correctly the main roadblock was CGO and some issue compiling due to the image processing library or something like that discuit uses. Might be able to take some time later this week to give a multi-arch build a try again.

**Comment by penchantlabs** [comment]
I managed to compile on arm64 without using docker. I had to install libvips using another method than the one you provided however.

I manually the commands in the example dockerfile here:
https://github.com/libvips/libvips/issues/3438

I did this with VIPS_VERSION=8.15.2

**Comment by Codycody31** [comment]
quick update, I have a workflow that can build both arm64 and amd64 images, however I can't seem to get to successfully build as a multi-arch with both for some reason. Once I get that figured out I should be able to put a PR together

**Comment by Codycody31** [comment]
I've got a working workflow now, @penchantlabs if you able to, could you give `discuit/discuit:aedccff5219bfefc283b7a06bde1cdea71eaac34` a try and see how that works for you? supports `linux/arm64` & `linux/amd64` I just need to see if the image stuff work correctly as I wasn't sure if vips is needed at runtime or just when the binary was compiled.

**Comment by penchantlabs** [comment]
Confirmed it to work with this dockerfile:

```
FROM insidiousfiddler/multiarch-discuit:latest

# Install libvips
RUN apt-get update && apt-get install -y libvips
```
