### ISSUE TITLE
[Suggestion] Sort by all

### ISSUE THREAD

**Issue by Kaamkiya** [discuitnet/discuit#133]
The current sort options don't include all, which is odd because it's built in already.

For example, https://discuit.net/?sort=all shows the most popular posts _of all time_, and https://discuit.net/?sort=year shows this year only. 

I'd like to make a PR for this.

EDIT: Looking closer, there is already a line of code for this, but it's hidden. Why is that?

**Comment by previnder** [comment]
> EDIT: Looking closer, there is already a line of code for this, but it's hidden. Why is that?

Because on the desktop view it makes the feed-sort-bar too long causing it to overflow, I removed the `All` option as a quick fix. At the time, that was totally fine, since Discuit was under a year old.

(![image](https://github.com/user-attachments/assets/89281756-112d-4138-b0e1-929d2116c554))

I think it's time to redesign this UI component. Perhaps a drop-down would be a better choice.

**Comment by Kaamkiya** [comment]
Ohhh, that makes sense. A dropdown would be good.

**Comment by Kaamkiya** [comment]
I'll start development on this.

**Comment by previnder** [comment]
Hey @Kaamkiya, I had to complete this as part of the feed compact mode add. Hope you don't mind.

**Comment by Kaamkiya** [comment]
That's alright. Thanks for implementing it :)
