### ISSUE TITLE
[BUG] discuit not loading 

### ISSUE THREAD

**Issue by ttaylor-st** [discuitnet/discuit#136]
since the last update, discuit hasn't been loading without doing a hard refresh (ctrl shift r) beforehand. had the following output in the console:

```
Registering the service-worker discuit.net:64:33
Loading failed for the module with source “https://discuit.net/assets/index-BP38H59v.js”. discuit.net:75:76
Failed to load ‘https://discuit.net/assets/index-BP38H59v.js’. A ServiceWorker intercepted the request and encountered an unexpected error. service-worker.js:1:1929
The stylesheet https://discuit.net/assets/index-BODeEx7U.css was not loaded because its MIME type, “text/html”, is not “text/css”. discuit.net
```

clearing cookies and site data fixed it. i'm still able to repro in another profile though 

happening on firefox 131.0.2 (64-bit), desktop

**Comment by previnder** [comment]
Took me a bit of time but found a way to reproduce the bug on `localhost`:

1. Build the site (back-end and front-end) and run it on `localhost`.
2. Open the `index-[hash].js` file of the site in the browser.
3. Kill the Go server.
4. Hard refresh the opened JS file to clear only that file from the browser cache.
5. Add a superficial line of code to the front-end to change the hashname of the next build output file (add something like `console.log('123');` to `App.jsx`).
6. Close the browser.
7. Build the front-end again.
8. Run the server.
9. Open the browser and goto 'localhost'. You should see a blank screen.

The source of the error is that the service-worker is looking for the front-end assets (the `.css` and `.js` files) but they're not to be found in the browser cache (specifically in `CacheStorage`), and the version of the files the service-worker is looking for is not to be found on the server as well, as they've been replaced with the newer build files. This bug was introduced when the migration from Webpack to Vite happened, as then the public path of the build assets changed (from `/app.[hash].js` to `/assets/index-[hash].js`, and likewise for the CSS files); the service-worker was not updated to reflect this change.

The solution would be to fix the service-worker, and also, for the time being, to not clear the `ui/dist` folder when re-building the front-end so as to keep the old assets.
